In [1]:
# Cell 1: Import and connect
import psycopg2
import pandas as pd
import yaml

with open('../configs/config.yml', 'r') as f:
    config = yaml.safe_load(f)

db = config['database']
conn = psycopg2.connect(
    host=db['host'],
    port=db['port'],
    database=db['database'],
    user=db['user'],
    password=db['password']
)

print("Connected to database")

Connected to database

In [2]:
# Cell 2: Check all requests
df_requests = pd.read_sql("""
    SELECT req_id, user_id, video_url, status, created_at 
    FROM requests 
    ORDER BY req_id DESC
""", conn)

print(f"Total requests: {len(df_requests)}")
df_requests

Total requests: 1

/tmp/ipykernel_157629/4187642023.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_requests = pd.read_sql("""

,req_id,user_id,video_url,status,created_at
0,1,5153676644,https://youtube.com/watch?v=udKO6rNilmQ&si=JyO...,FETCHED,2026-05-22 22:01:17.406723

In [3]:
# Cell 3: Check specific request (change req_id)
req_id = 1

df_single = pd.read_sql("""
    SELECT req_id, user_id, video_url, status, created_at 
    FROM requests 
    WHERE req_id = %s
""", conn, params=[req_id])

print(f"Request {req_id} status: {df_single.iloc[0]['status'] if not df_single.empty else 'Not found'}")
df_single

Request 1 status: FETCHED

/tmp/ipykernel_157629/2982890742.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_single = pd.read_sql("""

,req_id,user_id,video_url,status,created_at
0,1,5153676644,https://youtube.com/watch?v=udKO6rNilmQ&si=JyO...,FETCHED,2026-05-22 22:01:17.406723

In [4]:
# Cell 4: Show raw comments for a request
req_id = 1

df_comments = pd.read_sql("""
    SELECT comment_id, text_display, scraped_at 
    FROM raw_comments 
    WHERE req_id = %s 
    ORDER BY scraped_at
""", conn, params=[req_id])

print(f"Comments for request {req_id}: {len(df_comments)}")
df_comments.head(10)

Comments for request 1: 9

/tmp/ipykernel_157629/4117218879.py:4: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_comments = pd.read_sql("""

,comment_id,text_display,scraped_at
0,UgwoIZLP892OV1qVs6F4AaABAg,ကောင်းပါရဲသိချင်လေး❤❤❤❤❤❤❤❤❤ကြိုးစားနော်ခိုင်မ...,2026-05-22 22:12:56.694837
1,Ugw4-nkc81LiXQyv0v94AaABAg,အဆုံးထိထာဝရဆက်ပီးချစ်ပေးမယ် ​နော်။ကြိုကိနေတာကြ...,2026-05-22 22:12:56.694837
2,UgwXAvyX2BGl5Oqls1p4AaABAg,မောင်တစ်ယောက်ထဲဖြစ်မယ်ချစ်နေအုံးမယ်❤❤❤,2026-05-22 22:12:56.694837
3,UgyeNgIgAQ9szJeZMYR4AaABAg,❤❤,2026-05-22 22:12:56.694837
4,UgyFOXpT7dHOUsUMO-54AaABAg,❤❤❤❤❤❤❤.နှလုံးသား. ကြင်နာ. ထာဝရဖြစ်စေမည်.😊.❤.😊.,2026-05-22 22:12:56.694837
5,UgzpyBmtCW7uNyhvj694AaABAg,မာ,2026-05-22 22:12:56.694837
6,Ugxbr8yfvT0h71omECN4AaABAg,Amen. Thanks sing song with send song. Thanks....,2026-05-22 22:12:56.694837
7,UgwVg_zoyBo-fG3RBDh4AaABAg,အနမ်းလေးဆီးကြို မည်.So good. Thanks sing song ...,2026-05-22 22:12:56.694837
8,UgyeAR9Hc3ixa5Kj-Jp4AaABAg,စိတ်နာလက်စနဲ့ဆက်ပီးစိတ်နာကြတာပေါ့,2026-05-22 22:12:56.694837